os:
  - linux
language:
 - python
python:
 - '2.7'
 - '3.7'
install:
 - pip install -r dependencies.txt
 - pip install codecov
 - pip install pytest-cov
script:
 - pytest --cov=./  --cov-report=xml tests/
after_success:
 - codecov --file coverage.xml --token $CODECOV_TOKEN


